# Generated by Django 6.0.3 on 2026-03-15 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='enter a valid phone number ', regex='^\\d{10,15}$')])),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('birth_date', models.DateField(blank=True, max_length=10, null=True)),
                ('national_id', models.CharField(default='123456789012345678', max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must contain 18 digits', regex='^\\d{18}$')])),
                ('password', models.CharField(default='pbkdf2_sha256$1200000$oXG5bxEFR1vpJwWtJyEDRa$4G5IttbR6imgsn4sOy7JuQ6JS+VtcTyPTYWfhWoPrLI=', max_length=128)),
            ],
        ),
    ]
