# Generated by Django 6.0.3 on 2026-03-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1200000$EKfxKMZ8l9M1JBCvzl2X5X$KYoYo/EGO6VxUiXonhTcyGtq6WbDJUfR4CuW76U74Wg=', max_length=128),
        ),
    ]
