# Generated by Django 6.0.3 on 2026-03-15 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='enter a valid phone number ', regex='^\\d{10,15}$')])),
                ('email', models.EmailField(default='test@example.com', max_length=60, unique=True)),
                ('license_number', models.CharField(default='123456789', max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/images/')),
                ('active', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(default='pbkdf2_sha256$1200000$KPOAXsF75S6PWz4fZ1pim8$wBaC2aFO2QHfELsP/NRQnjvz6hzmD2iwI5FL+S+erZg=', max_length=128)),
            ],
        ),
    ]
