# Generated by Django 6.0.3 on 2026-03-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1200000$oeLlnKjErYPwQI85dvyO8e$dMtStZ585lVeyKIhkCNY0j9uZrt9Cw7RcfNJYR1o8zQ=', max_length=128),
        ),
    ]
